### ISSUE TITLE
Git icon

### ISSUE THREAD

**Issue by godhand1607** [skuridin/oh-my-zsh-node-theme#1]
How can i get the correct icon for git? 
<img width="19" alt="screen shot 2015-11-18 at 3 06 24 pm" src="https://cloud.githubusercontent.com/assets/7845870/11234762/10ac1bc0-8e06-11e5-8ab8-febd33edaa04.png">

**Comment by skuridin** [comment]
@godhand1607 Try to use [Hack](http://sourcefoundry.org/hack/) font in your terminal app.

**Comment by godhand1607** [comment]
Installed the font but I got the same results. I'm using iTerm2 btw. Got any more ideas? Sorry about this
<img width="613" alt="screen shot 2015-11-18 at 4 12 20 pm" src="https://cloud.githubusercontent.com/assets/7845870/11235797/5eb00a26-8e0f-11e5-9fb0-fd24a6dc4a48.png">

**Comment by skuridin** [comment]
@godhand1607 Check this symbol in Font Book please 
![screenshot 2015-11-18 13 17 06](https://cloud.githubusercontent.com/assets/929601/11235844/c3923450-8df6-11e5-816b-f2333d2ae0e5.png)

**Comment by godhand1607** [comment]
Found it. Maybe it's on the char encoding? i'm using utf-8
<img width="800" alt="screen shot 2015-11-18 at 4 23 53 pm" src="https://cloud.githubusercontent.com/assets/7845870/11235961/d256205e-8e10-11e5-9a72-287ca4a3a3a2.png">

**Comment by skuridin** [comment]
@godhand1607 Try to copy this symbol from the Font Book and replace the original one in the `node.zsh-theme`
 I'm using `utf-8` too.

**Comment by godhand1607** [comment]
Tried changing it and it's still the same

**Comment by skuridin** [comment]
@godhand1607 Sorry, I have no idea what else we can do

**Comment by puresick** [comment]
I had the same issue and had to use one of the patched fonts for the vim powerline plugin (https://github.com/powerline/fonts).
After installing one of these fonts, you have to change the Non-ASCII Font in your profile settings in iTerm to it. 
This is how it looks in my settings: 
![screen shot 2015-11-18 at 11 18 25](https://cloud.githubusercontent.com/assets/2714266/11238461/1ec3e000-8de6-11e5-9a7d-73ea19860d40.png).

**Comment by godhand1607** [comment]
@puresick Thanks! it's ok now. @skuridin Big thanks too!

**Comment by jalbertsr** [comment]
@puresick It worked well for me too! Thanks!!
